<?php
$apiKey = "rzp_test_tgSa5FDM1ythsc";

// Output messages
$responses = [];
// Check if the form was submitted
if (isset($_POST['email'], $_POST['name'], $_POST['mobile'])) {
	// Validate email adress
	if (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)) {
		$responses[] = 'Email is invalid!';
	}
	if ($_POST['mobile']<10)
		{
		$responses[] = 'Enter valid mobile number!';
	} 
	
	$phoneNumber = $_POST['mobile'];
	if(!empty($phoneNumber)) // phone number is not empty
	{
    if(!preg_match("/^[7-9]{1}[0-9]{9}$/i",$phoneNumber)) // phone number is valid
    {
      $responses[] = 'Enter valid mobile number!';
    }
	}
	
	// Make sure the form fields are not empty
	if (empty($_POST['email']) || empty($_POST['name']) || empty($_POST['mobile'])) {
		$responses[] = 'Please complete all fields!';
	}
}	

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount'] * $_POST['cost'] ;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
	data-name="EcoGo"
    data-description="Ride Easy with EcoGo"
    data-image="logo.png"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="#cc99ff"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

